/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['hello.js']) {
  _$jscoverage['hello.js'] = [];
  _$jscoverage['hello.js'][1] = 0;
  _$jscoverage['hello.js'][2] = 0;
  _$jscoverage['hello.js'][4] = 0;
  _$jscoverage['hello.js'][5] = 0;
  _$jscoverage['hello.js'][7] = 0;
  _$jscoverage['hello.js'][9] = 0;
  _$jscoverage['hello.js'][10] = 0;
  _$jscoverage['hello.js'][11] = 0;
  _$jscoverage['hello.js'][13] = 0;
}
_$jscoverage['hello.js'].source = ["<span class=\"k\">var</span> http <span class=\"k\">=</span> require<span class=\"k\">(</span><span class=\"s\">\"http\"</span><span class=\"k\">);</span>","<span class=\"k\">var</span> url <span class=\"k\">=</span> require<span class=\"k\">(</span><span class=\"s\">\"url\"</span><span class=\"k\">);</span>","","http<span class=\"k\">.</span>createServer<span class=\"k\">(</span><span class=\"k\">function</span><span class=\"k\">(</span>request<span class=\"k\">,</span> response<span class=\"k\">)</span> <span class=\"k\">{</span>","\t<span class=\"k\">var</span> urlParts <span class=\"k\">=</span> url<span class=\"k\">.</span>parse<span class=\"k\">(</span>request<span class=\"k\">.</span>url<span class=\"k\">,</span> <span class=\"k\">true</span><span class=\"k\">);</span>","","\tconsole<span class=\"k\">.</span>log<span class=\"k\">(</span><span class=\"s\">\"Server: ON\"</span><span class=\"k\">);</span>","","\tresponse<span class=\"k\">.</span>writeHead<span class=\"k\">(</span><span class=\"s\">200</span><span class=\"k\">,</span> <span class=\"k\">{</span><span class=\"s\">\"Content-Type\"</span><span class=\"k\">:</span><span class=\"s\">\"text/plain\"</span><span class=\"k\">}</span><span class=\"k\">);</span>","\tresponse<span class=\"k\">.</span>write<span class=\"k\">(</span><span class=\"s\">\"Hello, \"</span> <span class=\"k\">+</span> urlParts<span class=\"k\">.</span>query<span class=\"k\">[</span><span class=\"s\">\"name\"</span><span class=\"k\">]);</span>","\tresponse<span class=\"k\">.</span>end<span class=\"k\">();</span>","","\tconsole<span class=\"k\">.</span>log<span class=\"k\">(</span><span class=\"s\">\"Server: OFF\"</span><span class=\"k\">);</span>","<span class=\"k\">}</span><span class=\"k\">).</span>listen<span class=\"k\">(</span><span class=\"s\">8888</span><span class=\"k\">);</span>"];
_$jscoverage['hello.js'][1]++;
var http = require("http");
_$jscoverage['hello.js'][2]++;
var url = require("url");
_$jscoverage['hello.js'][4]++;
http.createServer((function (request, response) {
  _$jscoverage['hello.js'][5]++;
  var urlParts = url.parse(request.url, true);
  _$jscoverage['hello.js'][7]++;
  console.log("Server: ON");
  _$jscoverage['hello.js'][9]++;
  response.writeHead(200, {"Content-Type": "text/plain"});
  _$jscoverage['hello.js'][10]++;
  response.write(("Hello, " + urlParts.query.name));
  _$jscoverage['hello.js'][11]++;
  response.end();
  _$jscoverage['hello.js'][13]++;
  console.log("Server: OFF");
})).listen(8888);
